### ISSUE TITLE
Run without saving all the transactions

### ISSUE THREAD

**Issue by KirillLykov** [blockworks-foundation/simulate_mango_v3#5]
Since I'm planning to run sometimes mango-simulation for several hours, I believe that saving all the transactions might be impractical (transactions sampling might a good thing, but it is separate feature) because getting blocks takes long time and because the transactions file will be huge.
To avoid saving transactions, I've tried not specifying corresponding file name.
Yet this led to error in the logs like `Tx confirm record channel broken channel closed`, which happens in `process_blocks` function call.

**Comment by mschneider** [comment]
fyi you can just pipe to /dev/null
